### ISSUE TITLE
wrong paper in the readme?

### ISSUE THREAD

**Issue by Geal** [zcash/bn#3]
in the README, the paper link points to the [SNARK paper](https://eprint.iacr.org/2013/507). Shouldn't it be [Pairing-Friendly Elliptic Curves of Prime Order](https://eprint.iacr.org/2005/133)?

**Comment by ebfull** [comment]
Good catch, the link should be [[BCTV14]](http://eprint.iacr.org/2013/879) which explains that the curve instantiation we use is tailored for use in SNARKs. (We pick a special group order for efficiency purposes.) We also use some other optimizations that are cited in the paper. The BN paper you mention is the foundation of the construction, though.

I'm sorry if these papers lead you down a rabbit hole of confusing citations, I can try my best to clear things up for you or ask the cryptographers on our team for more information.

**Comment by ebfull** [comment]
Note that this library implements what is provided by the [ate-pairing](https://github.com/herumi/ate-pairing) library and is based on a (simpler) implementation our cryptographers implemented in [libsnark](https://github.com/scipr-lab/libsnark/).

**Comment by ebfull** [comment]
I updated the README to point to the current best description of our curve and optimizations, though it's not incredibly formal or detailed.
